### ISSUE TITLE
Please add some log in vscode output

### ISSUE THREAD

**Issue by jackalcooper** [notskm/vscode-clang-tidy#1]
First, thanks for your work on this extension. 
Is it possible to add some log information in VS Code's output panel (View -> Output)?
I could only get the diagnostics from limited files. It would be great if there is some logging so it is easier to figure out what goes wrong.

Thanks again.

**Comment by notskm** [comment]
At the very least, I could `console.log` some information, but I'll look into using the output panel if it makes sense.

Also, could you please provide some more detail about the problem? Directory layout, filenames of problematic files, any other information you think may be relevant.

**Comment by notskm** [comment]
I'm logging the clang-tidy command invocation and the raw clang-tidy output now, see #2. It's available in master, but not released yet. Let me know if there's any other info you'd like to see in the logs.

**Comment by notskm** [comment]
Released in version 0.2.0.

**Comment by jackalcooper** [comment]
I just found out that the official clangd vscode extension by LLVM now integrates clang tide and clang format altogether if you are using LLVM 9.

**Comment by jackalcooper** [comment]
check this out: https://clang.llvm.org/extra/clangd/Features.html#id10

**Comment by notskm** [comment]
Yeah, I've seen that. I love the idea of clang-tidy being part of language servers. Unfortunately, clangd doesn't work as well as other language servers for me. It has been a little while since I've tried it, though. I think there's still plenty of value in this extension.

**Comment by jackalcooper** [comment]
I see. I also found the integration not that useful since it didn't give me any useful information about my code.
