### ISSUE TITLE
Allow clang-tidy to ignore specific folders

### ISSUE THREAD

**Issue by geiseri** [notskm/vscode-clang-tidy#17]
It seems that there is no way to ignore folders in the workspace.  This is an issue for me since I do not want to run tidy on my tests directory..

**Comment by notskm** [comment]
I've been thinking about adding a blacklist for a while. I'll look into that soon.

**Comment by HorstBaerbel** [comment]
Another use case: It is also necessary to exclude the build directory when using CMake...

**Comment by notskm** [comment]
Done as of #33
