### ISSUE TITLE
clang-tidy.buildPath not working

### ISSUE THREAD

**Issue by Schneegans** [notskm/vscode-clang-tidy#21]
I am struggling getting the `clang-tidy.buildPath` to work. When used like this:

```json
"clang-tidy.buildPath": "build/linux-release"
```

I get the error `No compilation database found in [...absolute workspace path...]/"build/linux-release" or any parent directory`. I think the issue is the superfluous `"` before `"build`. How can I get rid of this?

Thank you!

**Comment by knehez** [comment]
By hand, modify this: \.vscode\extensions\notskm.clang-tidy-0.4.1\out\tidy.js 
line 30 (remove ""), and restart VS code

**Comment by lpc921** [comment]
This worked for me

**Comment by Schneegans** [comment]
Thanks!
