### ISSUE TITLE
Support fixing directly in warning (currently "No fixes available" is shown)

### ISSUE THREAD

**Issue by pavel-the-best** [notskm/vscode-clang-tidy#42]

**Comment by Trass3r** [comment]
Took me a while just to find the API for that:
https://code.visualstudio.com/api/references/vscode-api#TextEdit
https://code.visualstudio.com/api/references/vscode-api#WorkspaceEdit
https://code.visualstudio.com/api/references/vscode-api#CodeAction
There's also an interesting SourceFixAll CodeActionKind that could be used for the apply all fixits functionality.

**Comment by Trass3r** [comment]
Reference: https://github.com/alesiong/clang-tidy-linter/commit/c0709b64c03374c9c93571b0474376ba2dbe45e4#diff-916156c481141bfcd08c6ae40ce10e00

**Comment by dmeister** [comment]
While I realize that this project is in hiatus, I have put a pull request out. Given the high number of clang-tidy checks with fix support, this feature makes vscode-clang-tidy much more useful.

**Comment by notskm** [comment]
I've accepted @dmeister's pull request. Look out for it whenever I get around to a new release.
