### ISSUE TITLE
Officially putting this project on hiatus

### ISSUE THREAD

**Issue by notskm** [notskm/vscode-clang-tidy#45]
I don't have the time or work on this project at all at the moment. What free time I have, I would like to spend on other things. I'm also about to start college, which will further limit the amount of time I can spend on this.

As a result, this project is being put on hiatus.

**Comment by Adobe-Android** [comment]
Sad to see it, but I understand. Good luck with your future endeavors!

**Comment by iluetkeb** [comment]
Maybe you could put this info into the README and/or the information displayed in VS Code when installing.

**Comment by mfiumara** [comment]
Any intention to transfer ownership to other developers? I'd gladly help.

**Comment by notskm** [comment]
@mfiumara Transferring ownership is an option, but I don't see the point when the project can just be forked. Another option is adding a collaborator with push rights.

Over the winter, I'll only be taking one class. Since I should have some extra time, I might at least clean up the codebase and make sure everything's working.

**Comment by mfiumara** [comment]
@notskm I think someone with push rights is also fine, the downside of a fork is that it would appear in the vscode store as a fork while the original has a good rating already.

**Comment by notskm** [comment]
Closing this issue. I'm working on the project again. School starts up again soon, so we'll see how much time I can put into this.
