### ISSUE TITLE
regular expression 

### ISSUE THREAD

**Issue by caichencn** [notskm/vscode-clang-tidy#48]
In source code file tidy.ts，I can not understand line 175，What is this regular expression searching for？ 

`const yamlIndex = clangTidyOutput.search(/^---$/m);`

Does it search for three consecutive ‘-’ ？ why?

**Comment by notskm** [comment]
> Does it search for three consecutive ‘-’ ？ why?

Yes. If I remember correctly, clang-tidy outputs a bunch of human readable diagnostic information before the yaml that the extension needs. The three dashes mark the start of the yaml.

**Comment by caichencn** [comment]
> > Does it search for three consecutive ‘-’ ？ why?
> 
> Yes. If I remember correctly, clang-tidy outputs a bunch of human readable diagnostic information before the yaml that the extension needs. The three dashes mark the start of the yaml.

Ok, That's it，I need to learn more, thank you!
