### ISSUE TITLE
Feature request: multi-root workspace support

### ISSUE THREAD

**Issue by YunHsiao** [notskm/vscode-clang-tidy#57]
Currently, the extension settings do not apply in a multi-root workspace environment. The official doc gives [detailed instructions](https://github.com/microsoft/vscode/wiki/Adopting-Multi-Root-Workspace-APIs) on adopting this. Would be really helpful if this can be done.

**Comment by YunHsiao** [comment]
Oh, and btw, it would be helpful too if there is a command to manually trigger auto fixing the current file

**Comment by zertrin** [comment]
Why was this feature request closed?

As far as I can see, this is not available currently, so this request could stay open.

I needed to set a setting only in a given folder of a multi-root workspace, but the settings for the clang-tidy extension can only be set at workspace level, not in the individual folders that compose this multi-root workspace.

**Comment by YunHsiao** [comment]
The extension author seems no longer active on the project, I've switched to `clangd` + `Command Runner` instead, it works much more smoothly than this.

**Comment by notskm** [comment]
You're correct. I have not been actively maintaining this project. I don't want to say I won't return to it, but college has eaten up nearly all of my time.

**Comment by YunHsiao** [comment]
For anyone who struggles with setting up vscode clang-tidy environment, [here](https://github.com/cocos-creator/engine-native/blob/develop/docs/LINTER_AUTOFIX_GUIDE.md) is the setup tutorial for our production environment using `clangd`. @notskm maybe you can take a look and make some alternative recommendations on the project readme page for the moment?
