### ISSUE TITLE
error: 'stddef.h' file not found [clang-diagnostic-error]

### ISSUE THREAD

**Issue by MrVermond** [notskm/vscode-clang-tidy#6]
Hey there,
i just have a question:
after installing the clang tidy extension and setup the path to the bin, i receive errors while the checkts which says that system header files are not found. Do you know how to fix this issue?
Ive tried to setup the -p parameter but wasn succesfull.

Thanks in advance
Nick

**Comment by notskm** [comment]
That doesn't sound like an issue with the extension. Does this happen when running clang-tidy manually? If so, the best I can say is to Google the error.

I found this. Maybe it'll be helpful?
https://stackoverflow.com/questions/20587228/clang-error-stddef-file-not-found

**Comment by MrVermond** [comment]
Hi @notskm ,

thank you for the hint, i will check it out the next days.
