### ISSUE TITLE
No quick fixes available in vscode

### ISSUE THREAD

**Issue by DenisPryt** [notskm/vscode-clang-tidy#65]
There is an option ti use fix on save, but VSCode hind show that "No quick fixes available".
Is there any way to use fixes without autosave but from vscode hint?

**Comment by notskm** [comment]
This was implemented in a pull request months ago, but has not yet been released. I had some things I wanted to fix up first, but I haven't had time due to college.

**Comment by DenisPryt** [comment]
Thanks for reply

**Comment by DylanSp** [comment]
Any idea when you'll release a new version with this PR? This is already a very handy extension, but being able to run fixes as quick fixes would be really useful.
